# Generated by Django 4.1 on 2023-01-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_columns', models.BinaryField()),
                ('customer_columns', models.BinaryField()),
                ('survey_columns', models.BinaryField()),
                ('menu_columns', models.BinaryField()),
                ('conversion_columns', models.BinaryField()),
                ('content', models.BinaryField()),
            ],
        ),
    ]
