# Generated by Django 4.1 on 2023-01-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Top', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
