# Generated by Django 4.1 on 2023-01-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Top', '0002_usersettings_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='content',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='conversion_columns',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='customer_columns',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='menu_columns',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='platform_columns',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='survey_columns',
            field=models.BinaryField(default=None),
        ),
    ]
