# Generated by Django 4.1 on 2023-01-18 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Top', '0005_usersettings_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='all_columns',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='content',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user_data',
            field=models.BinaryField(),
        ),
    ]
