# Generated by Django 4.1 on 2023-01-18 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Top', '0006_alter_usersettings_all_columns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='user_data',
        ),
    ]
