# Generated by Django 4.1 on 2023-02-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Top', '0007_remove_usersettings_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='conversion_columns',
            field=models.BinaryField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='customer_columns',
            field=models.BinaryField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='menu_columns',
            field=models.BinaryField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='platform_columns',
            field=models.BinaryField(max_length=300),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='survey_columns',
            field=models.BinaryField(max_length=300),
        ),
    ]
