# Generated by Django 4.1 on 2023-02-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('platform', models.TextField(null=True)),
                ('customer', models.TextField(null=True)),
                ('survey', models.TextField(null=True)),
                ('menu', models.TextField(null=True)),
                ('channel', models.TextField(null=True)),
                ('conversion', models.TextField(null=True)),
            ],
        ),
    ]
