# Generated by Django 4.1 on 2023-02-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ColumnSettings', '0002_alter_columnsettings_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnsettings',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='columnsettings',
            name='conversion',
        ),
        migrations.RemoveField(
            model_name='columnsettings',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='columnsettings',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='columnsettings',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='columnsettings',
            name='survey',
        ),
    ]
