# Generated by Django 4.1 on 2023-02-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColumnSettings', '0003_remove_columnsettings_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnsettings',
            name='channel',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='columnsettings',
            name='conversion',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='columnsettings',
            name='customer',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='columnsettings',
            name='menu',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='columnsettings',
            name='platform',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='columnsettings',
            name='survey',
            field=models.BinaryField(null=True),
        ),
    ]
